import java.util.ArrayList;
import java.util.Collection;

import org.htmlparser.Node;
import org.htmlparser.NodeFilter;
import org.htmlparser.Parser;
import org.htmlparser.filters.NodeClassFilter;
import org.htmlparser.nodes.TagNode;
import org.htmlparser.tags.TableRow;
import org.htmlparser.util.NodeList;
import org.htmlparser.util.ParserException;

import scraper.utils.HtmlUtils;


public class ScrapTest {
  
  public static void main(String[] args) throws ParserException {
	  Collection<String> urls = new ArrayList<String>();
	  String host = "http://";
	  urls.add("www.movistar.net.ar/equipos/popup/airam-2200_descripcion.html");
	  urls.add("www.movistar.net.ar/equipos/popup/airam-342.html");
	  urls.add("www.movistar.net.ar/equipos/popup/airam-tsm211.html");
	  urls.add("www.movistar.net.ar/equipos/popup/airam-tsm340.html");
	  urls.add("www.movistar.net.ar/equipos/popup/airam.html");
	  urls.add("www.movistar.net.ar/equipos/popup/alcatel-332a.html");
	  urls.add("www.movistar.net.ar/equipos/popup/alcatel-c701a.html");
	  urls.add("www.movistar.net.ar/equipos/popup/alcatel-ot155a.html");
	  urls.add("www.movistar.net.ar/equipos/popup/alcatel-ot156a.html");
	  urls.add("www.movistar.net.ar/equipos/popup/alcatel-ot158a.html");
	  urls.add("www.movistar.net.ar/equipos/popup/alcatel-ot159a.html");
	  urls.add("www.movistar.net.ar/equipos/popup/alcatel-ot161a.html");
	  urls.add("www.movistar.net.ar/equipos/popup/alcatel-ot552a.html");
	  urls.add("www.movistar.net.ar/equipos/popup/alcatel-ot557.html");
	  urls.add("www.movistar.net.ar/equipos/popup/alcatel-ot801a.html");
	  urls.add("www.movistar.net.ar/equipos/popup/alcatel-otc550a.html");
	  urls.add("www.movistar.net.ar/equipos/popup/alcatel-otc652a.html");
	  urls.add("www.movistar.net.ar/equipos/popup/alcatel-ots853a.html");
	  urls.add("www.movistar.net.ar/equipos/popup/benq-ef51.html");
	  urls.add("www.movistar.net.ar/equipos/popup/benq-p50.html");
	  urls.add("www.movistar.net.ar/equipos/popup/blackberry-7100.html");
	  urls.add("www.movistar.net.ar/equipos/popup/blackberry-7290.html");
	  urls.add("www.movistar.net.ar/equipos/popup/blackberry-8100pearl.html");
	  urls.add("www.movistar.net.ar/equipos/popup/blackberry-8110.html");
	  urls.add("www.movistar.net.ar/equipos/popup/blackberry-8120.html");
	  urls.add("www.movistar.net.ar/equipos/popup/blackberry-8300curve.html");
	  urls.add("www.movistar.net.ar/equipos/popup/blackberry-8310.html");
	  urls.add("www.movistar.net.ar/equipos/popup/blackberry-8320.html");
	  urls.add("www.movistar.net.ar/equipos/popup/blackberry-8700g.html");
	  urls.add("www.movistar.net.ar/equipos/popup/blackberry-8800.html");
	  urls.add("www.movistar.net.ar/equipos/popup/ericsson-j100.html");
	  urls.add("www.movistar.net.ar/equipos/popup/ericsson-k200a.html");
	  urls.add("www.movistar.net.ar/equipos/popup/ericsson-k300.html");
	  urls.add("www.movistar.net.ar/equipos/popup/ericsson-k550.html");
	  urls.add("www.movistar.net.ar/equipos/popup/ericsson-k790.html");
	  urls.add("www.movistar.net.ar/equipos/popup/ericsson-k850.html");
	  urls.add("www.movistar.net.ar/equipos/popup/ericsson-p910.html");
	  urls.add("www.movistar.net.ar/equipos/popup/ericsson-s710.html");
	  urls.add("www.movistar.net.ar/equipos/popup/ericsson-t106.html");
	  urls.add("www.movistar.net.ar/equipos/popup/ericsson-t226.html");
	  urls.add("www.movistar.net.ar/equipos/popup/ericsson-t237.html");
	  urls.add("www.movistar.net.ar/equipos/popup/ericsson-t290.html");
	  urls.add("www.movistar.net.ar/equipos/popup/ericsson-t300.html");
	  urls.add("www.movistar.net.ar/equipos/popup/ericsson-t616.html");
	  urls.add("www.movistar.net.ar/equipos/popup/ericsson-t637.html");
	  urls.add("www.movistar.net.ar/equipos/popup/ericsson-w200.html");
	  urls.add("www.movistar.net.ar/equipos/popup/ericsson-w300i.html");
	  urls.add("www.movistar.net.ar/equipos/popup/ericsson-w380.html");
	  urls.add("www.movistar.net.ar/equipos/popup/ericsson-w580.html");
	  urls.add("www.movistar.net.ar/equipos/popup/ericsson-w600.html");
	  urls.add("www.movistar.net.ar/equipos/popup/ericsson-w710.html");
	  urls.add("www.movistar.net.ar/equipos/popup/ericsson-w800.html");
	  urls.add("www.movistar.net.ar/equipos/popup/ericsson-w810i.html");
	  urls.add("www.movistar.net.ar/equipos/popup/ericsson-z300.html");
	  urls.add("www.movistar.net.ar/equipos/popup/ericsson-z310i.html");
	  urls.add("www.movistar.net.ar/equipos/popup/ericsson-z320.html");
	  urls.add("www.movistar.net.ar/equipos/popup/ericsson-z500.html");
	  urls.add("www.movistar.net.ar/equipos/popup/ericsson-z520.html");
	  urls.add("www.movistar.net.ar/equipos/popup/ericsson-z550.html");
	  urls.add("www.movistar.net.ar/equipos/popup/ericssonk310.html");
	  urls.add("www.movistar.net.ar/equipos/popup/handspring-treo600.html");
	  urls.add("www.movistar.net.ar/equipos/popup/handspring-treo650.html");
	  urls.add("www.movistar.net.ar/equipos/popup/handspring-treo680.html");
	  urls.add("www.movistar.net.ar/equipos/popup/handspring-treo750.html");
	  urls.add("www.movistar.net.ar/equipos/popup/lg-g4015.html");
	  urls.add("www.movistar.net.ar/equipos/popup/lg-ke990.html");
	  urls.add("www.movistar.net.ar/equipos/popup/lg-kf600.html");
	  urls.add("www.movistar.net.ar/equipos/popup/lg-kp215.html");
	  urls.add("www.movistar.net.ar/equipos/popup/lg-me770.html");
	  urls.add("www.movistar.net.ar/equipos/popup/lg-me850.html");
	  urls.add("www.movistar.net.ar/equipos/popup/lg-me970.html");
	  urls.add("www.movistar.net.ar/equipos/popup/lg-mg110.html");
	  urls.add("www.movistar.net.ar/equipos/popup/lg-mg120.html");
	  urls.add("www.movistar.net.ar/equipos/popup/lg-mg160.html");
	  urls.add("www.movistar.net.ar/equipos/popup/lg-mg200.html");
	  urls.add("www.movistar.net.ar/equipos/popup/lg-mg230.html");
	  urls.add("www.movistar.net.ar/equipos/popup/lg-mg280.html");
	  urls.add("www.movistar.net.ar/equipos/popup/lg-mg295.html");
	  urls.add("www.movistar.net.ar/equipos/popup/lg-mg810.html");
	  urls.add("www.movistar.net.ar/equipos/popup/lg-mu500.html");
	  urls.add("www.movistar.net.ar/equipos/popup/motorola-a1200.html");
	  urls.add("www.movistar.net.ar/equipos/popup/motorola-c115.html");
	  urls.add("www.movistar.net.ar/equipos/popup/motorola-c139.html");
	  urls.add("www.movistar.net.ar/equipos/popup/motorola-c155.html");
	  urls.add("www.movistar.net.ar/equipos/popup/motorola-c200.html");
	  urls.add("www.movistar.net.ar/equipos/popup/motorola-c202.html");
	  urls.add("www.movistar.net.ar/equipos/popup/motorola-c261.html");
	  urls.add("www.movistar.net.ar/equipos/popup/motorola-c350.html");
	  urls.add("www.movistar.net.ar/equipos/popup/motorola-c381p.html");
	  urls.add("www.movistar.net.ar/equipos/popup/motorola-c650.html");
	  urls.add("www.movistar.net.ar/equipos/popup/motorola-c651.html");
	  urls.add("www.movistar.net.ar/equipos/popup/motorola-e380.html");
	  urls.add("www.movistar.net.ar/equipos/popup/motorola-erockr.html");
	  urls.add("www.movistar.net.ar/equipos/popup/motorola-k1.html");
	  urls.add("www.movistar.net.ar/equipos/popup/motorola-q.html");
	  urls.add("www.movistar.net.ar/equipos/popup/motorola-razrv3.html");
	  urls.add("www.movistar.net.ar/equipos/popup/motorola-rokre2.html");
	  urls.add("www.movistar.net.ar/equipos/popup/motorola-slvrl7.html");
	  urls.add("www.movistar.net.ar/equipos/popup/motorola-u3.html");
	  urls.add("www.movistar.net.ar/equipos/popup/motorola-u6.html");
	  urls.add("www.movistar.net.ar/equipos/popup/motorola-u9.html");
	  urls.add("www.movistar.net.ar/equipos/popup/motorola-v172.html");
	  urls.add("www.movistar.net.ar/equipos/popup/motorola-v180.html");
	  urls.add("www.movistar.net.ar/equipos/popup/motorola-v186.html");
	  urls.add("www.movistar.net.ar/equipos/popup/motorola-v190ptt.html");
	  urls.add("www.movistar.net.ar/equipos/popup/motorola-v220.html");
	  urls.add("www.movistar.net.ar/equipos/popup/motorola-v220i.html");
	  urls.add("www.movistar.net.ar/equipos/popup/motorola-v235.html");
	  urls.add("www.movistar.net.ar/equipos/popup/motorola-v300.html");
	  urls.add("www.movistar.net.ar/equipos/popup/motorola-v360.html");
	  urls.add("www.movistar.net.ar/equipos/popup/motorola-v365p.html");
	  urls.add("www.movistar.net.ar/equipos/popup/motorola-v3e.html");
	  urls.add("www.movistar.net.ar/equipos/popup/motorola-v3i.html");
	  urls.add("www.movistar.net.ar/equipos/popup/motorola-v400p.html");
	  urls.add("www.movistar.net.ar/equipos/popup/motorola-v555.html");
	  urls.add("www.movistar.net.ar/equipos/popup/motorola-v600.html");
	  urls.add("www.movistar.net.ar/equipos/popup/motorola-v66i.html");
	  urls.add("www.movistar.net.ar/equipos/popup/motorola-v8.html");
	  urls.add("www.movistar.net.ar/equipos/popup/motorola-w220.html");
	  urls.add("www.movistar.net.ar/equipos/popup/motorola-w375.html");
	  urls.add("www.movistar.net.ar/equipos/popup/motorola-w5.html");
	  urls.add("www.movistar.net.ar/equipos/popup/motorola-w510.html");
	  urls.add("www.movistar.net.ar/equipos/popup/motorola-z6.html");
	  urls.add("www.movistar.net.ar/equipos/popup/nokia-1100.html");
	  urls.add("www.movistar.net.ar/equipos/popup/nokia-1108.html");
	  urls.add("www.movistar.net.ar/equipos/popup/nokia-1112.html");
	  urls.add("www.movistar.net.ar/equipos/popup/nokia-1208.html");
	  urls.add("www.movistar.net.ar/equipos/popup/nokia-1600.html");
	  urls.add("www.movistar.net.ar/equipos/popup/nokia-2600.html");
	  urls.add("www.movistar.net.ar/equipos/popup/nokia-2630.html");
	  urls.add("www.movistar.net.ar/equipos/popup/nokia-2651.html");
	  urls.add("www.movistar.net.ar/equipos/popup/nokia-2760.html");
	  urls.add("www.movistar.net.ar/equipos/popup/nokia-3100.html");
	  urls.add("www.movistar.net.ar/equipos/popup/nokia-3120.html");
	  urls.add("www.movistar.net.ar/equipos/popup/nokia-3200.html");
	  urls.add("www.movistar.net.ar/equipos/popup/nokia-3220.html");
	  urls.add("www.movistar.net.ar/equipos/popup/nokia-3620.html");
	  urls.add("www.movistar.net.ar/equipos/popup/nokia-3650.html");
	  urls.add("www.movistar.net.ar/equipos/popup/nokia-5070.html");
	  urls.add("www.movistar.net.ar/equipos/popup/nokia-5200.html");
	  urls.add("www.movistar.net.ar/equipos/popup/nokia-5300.html");
	  urls.add("www.movistar.net.ar/equipos/popup/nokia-5310.html");
	  urls.add("www.movistar.net.ar/equipos/popup/nokia-5700.html");
	  urls.add("www.movistar.net.ar/equipos/popup/nokia-6020.html");
	  urls.add("www.movistar.net.ar/equipos/popup/nokia-6061.html");
	  urls.add("www.movistar.net.ar/equipos/popup/nokia-6070.html");
	  urls.add("www.movistar.net.ar/equipos/popup/nokia-6101.html");
	  urls.add("www.movistar.net.ar/equipos/popup/nokia-6103.html");
	  urls.add("www.movistar.net.ar/equipos/popup/nokia-6131.html");
	  urls.add("www.movistar.net.ar/equipos/popup/nokia-6170.html");
	  urls.add("www.movistar.net.ar/equipos/popup/nokia-6230.html");
	  urls.add("www.movistar.net.ar/equipos/popup/nokia-6267.html");
	  urls.add("www.movistar.net.ar/equipos/popup/nokia-6620.html");
	  urls.add("www.movistar.net.ar/equipos/popup/nokia-6682.html");
	  urls.add("www.movistar.net.ar/equipos/popup/nokia-6820.html");
	  urls.add("www.movistar.net.ar/equipos/popup/nokia-7250i.html");
	  urls.add("www.movistar.net.ar/equipos/popup/nokia-7280.html");
	  urls.add("www.movistar.net.ar/equipos/popup/nokia-8801.html");
	  urls.add("www.movistar.net.ar/equipos/popup/nokia-9300.html");
	  urls.add("www.movistar.net.ar/equipos/popup/nokia-d311.html");
	  urls.add("www.movistar.net.ar/equipos/popup/nokia-e50.html");
	  urls.add("www.movistar.net.ar/equipos/popup/nokia-e61.html");
	  urls.add("www.movistar.net.ar/equipos/popup/nokia-e62.html");
	  urls.add("www.movistar.net.ar/equipos/popup/nokia-e65.html");
	  urls.add("www.movistar.net.ar/equipos/popup/nokia-n73.html");
	  urls.add("www.movistar.net.ar/equipos/popup/nokia-n80.html");
	  urls.add("www.movistar.net.ar/equipos/popup/nokia-n95.html");
	  urls.add("www.movistar.net.ar/equipos/popup/nokia-ngageqd.html");
	  urls.add("www.movistar.net.ar/equipos/popup/qtek-o8015.html");
	  urls.add("www.movistar.net.ar/equipos/popup/samsung-a706.html");
	  urls.add("www.movistar.net.ar/equipos/popup/samsung-c165.html");
	  urls.add("www.movistar.net.ar/equipos/popup/samsung-c207.html");
	  urls.add("www.movistar.net.ar/equipos/popup/samsung-c266.html");
	  urls.add("www.movistar.net.ar/equipos/popup/samsung-c275.html");
	  urls.add("www.movistar.net.ar/equipos/popup/samsung-c406.html");
	  urls.add("www.movistar.net.ar/equipos/popup/samsung-c425.html");
	  urls.add("www.movistar.net.ar/equipos/popup/samsung-c506.html");
	  urls.add("www.movistar.net.ar/equipos/popup/samsung-d836.html");
	  urls.add("www.movistar.net.ar/equipos/popup/samsung-d900.html");
	  urls.add("www.movistar.net.ar/equipos/popup/samsung-e116.html");
	  urls.add("www.movistar.net.ar/equipos/popup/samsung-e256.html");
	  urls.add("www.movistar.net.ar/equipos/popup/samsung-e316.html");
	  urls.add("www.movistar.net.ar/equipos/popup/samsung-e376.html");
	  urls.add("www.movistar.net.ar/equipos/popup/samsung-e496.html");
	  urls.add("www.movistar.net.ar/equipos/popup/samsung-e736.html");
	  urls.add("www.movistar.net.ar/equipos/popup/samsung-f250.html");
	  urls.add("www.movistar.net.ar/equipos/popup/samsung-i617.html");
	  urls.add("www.movistar.net.ar/equipos/popup/samsung-t519.html");
	  urls.add("www.movistar.net.ar/equipos/popup/samsung-t809.html");
	  urls.add("www.movistar.net.ar/equipos/popup/samsung-u600.html");
	  urls.add("www.movistar.net.ar/equipos/popup/samsung-x156.html");
	  urls.add("www.movistar.net.ar/equipos/popup/samsung-x426.html");
	  urls.add("www.movistar.net.ar/equipos/popup/samsung-x467.html");
	  urls.add("www.movistar.net.ar/equipos/popup/samsung-x486.html");
	  urls.add("www.movistar.net.ar/equipos/popup/samsung-x495.html");
	  urls.add("www.movistar.net.ar/equipos/popup/samsung-x576.html");
	  urls.add("www.movistar.net.ar/equipos/popup/samsung-x636.html");
	  urls.add("www.movistar.net.ar/equipos/popup/samsung-x836.html");
	  urls.add("www.movistar.net.ar/equipos/popup/sendo-m551.html");
	  urls.add("www.movistar.net.ar/equipos/popup/siemens-a56.html");
	  urls.add("www.movistar.net.ar/equipos/popup/siemens-a71.html");
	  urls.add("www.movistar.net.ar/equipos/popup/siemens-a76.html");
	  urls.add("www.movistar.net.ar/equipos/popup/siemens-c66.html");
	  urls.add("www.movistar.net.ar/equipos/popup/siemens-cf76.html");
	  urls.add("www.movistar.net.ar/equipos/popup/siemens-m56.html");
	  urls.add("www.movistar.net.ar/equipos/popup/siemens-s65.html");
	  Parser parser = new Parser();	  
	  for (String url : urls) {
		  
		  String html = HtmlUtils.getHtml(host+url);
		  parser.reset();
		  parser.setInputHTML(html);
		  NodeFilter filter = new NodeClassFilter(TableRow.class);
		  NodeList list = parser.extractAllNodesThatMatch(filter);
		  for (int i=0; list.elements().hasMoreNodes(); i++) {
			  Node nextNode = (TagNode)list.elements().nextNode();
			  System.out.println(nextNode.getText());
		  }
	  }
  }
}

//Lexer lexer = new Lexer();
//ParserFeedback pfb = null;
//FeedbackManager.setParserFeedback(pfb);
//NodeIterator nodeIter = new IteratorImpl(lexer,pfb);
